#%RAML 1.0
title: Accounts API
version: v1
baseUri: /api

/accounts:
  post:
    description: Create a new account

    body:
      application/json:
        example:
          {
            "name": "John",
            "phone": "9876543210",
            "email": "john@test.com",
            "username": "john123",
            "password": "john123",
            "accountType": "Tier I"
          }

    responses:
      201:
        body:
          application/json:
            example:
              {
                "accountId": 1001,
                "message": "Account Created Successfully"
              }

      400:
        body:
          application/json:
            example:
              {
                "code": 400,
                "message": "Validation Failed"
              }

      500:
        body:
          application/json:
            example:
              {
                "code": 500,
                "message": "Internal Server Error"
              }

  /{accountId}:
    get:
      description: Get account details by account id

      responses:
        200:
          body:
            application/json:
              example:
                {
                  "accountId": 1001,
                  "rewardPoints": 500,
                  "active": "YES"
                }

        404:
          body:
            application/json:
              example:
                {
                  "code": 404,
                  "message": "Account Not Found"
                }

        500:
          body:
            application/json:
              example:
                {
                  "code": 500,
                  "message": "Internal Server Error"
                }
                
                