name: SAPI CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hr-ticket-sapii

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Maven
        run: mvn -version

      - name: Check Secrets
        run: |
          echo "USERNAME LENGTH: ${#ANYPOINT_USERNAME}"
          echo "PASSWORD EXISTS: $([ -n "$ANYPOINT_PASSWORD" ] && echo YES || echo NO)"
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
