name: SAPI CI

on:
  push:
    branches:
      - develop
    paths:
      - 'hr-ticket-sapii/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hr-ticket-sapii

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Maven
        run: mvn -version

      - name: Build Project
        run: mvn clean package -DskipTests
